config/routes.rb
JoruriGw::Application.routes.draw do

  root :to => 'gw/admin/portal#index'

  match '_admin'                 => 'sys/admin/users#index'
  match '_admin.:format'         => 'sys/admin/users#index'
  match '_admin/login.:format'   => 'sys/admin/account#login'
  match '_admin/login'           => 'sys/admin/account#login'
  match '_admin/logout.:format'  => 'sys/admin/account#logout'
  match '_admin/logout'          => 'sys/admin/account#logout'
  match '_admin/account.:format' => 'sys/admin/account#info'
  match '_admin/account'         => 'sys/admin/account#info'
  match "_admin/sso"             => "sys/admin/account#sso"
  match '_admin/air_login'       => 'sys/admin/air#old_login'
  match '_admin/air_sso'         => 'sys/admin/air#login'
  match '_admin/cms'             => 'sys/admin/front#index'
  match '_admin/sys'             => 'sys/admin/front#index'
  match '_admin/system'          => 'sys/admin/front#index'

  Dir::entries("#{Rails.root}/config/modules").each do |mod|
    next if mod =~ /^\.+$/
    file = "#{Rails.root}/config/modules/#{mod}/routes.rb"
    load(file) if FileTest.exist?(file)
  end
  
  match '/tab_main/:id'  => 'gw/admin/tab_main#show'
  match '/siteinfo'      => 'gwboard/admin/siteinfo#index'
  match '/syntheses'     => 'gwboard/admin/syntheses#index'
  
  def admin_attaches(sys)
    match "_admin/_attaches/#{sys}/:title_id/:name/:u_code/:d_code", :to => "attaches/admin/#{sys}#download", :format => false
    match "_admin/_attaches/#{sys}/:title_id/:name/:u_code/:d_code/*filename", :to => "attaches/admin/#{sys}#download", :format => false

    match "_admin/attaches/#{sys}/:title_id/:name/:u_code/:d_code", :to => "attaches/admin/#{sys}#download", :format => false
    match "_admin/attaches/#{sys}/:title_id/:name/:u_code/:d_code/*filename", :to => "attaches/admin/#{sys}#download", :format => false
  end
  
  admin_attaches('gwqa')
  admin_attaches('gwbbs')
  admin_attaches('gwfaq')
  admin_attaches('doclibrary')
  admin_attaches('digitallibrary')
  admin_attaches('gwcircular')
  admin_attaches('gwworkflow')
  admin_attaches('gwmonitor')
  admin_attaches('gwmonitor_base')
  admin_attaches('gwworkflow')
  
  match '403.:format' => 'exception#index'
  match '404.:format' => 'exception#index'
  match '500.:format' => 'exception#index'
  match '*path'       => 'exception#index'

end

app/models/gwworkflow/doc.rb
# -*- encoding: utf-8 -*-

# 対象データベースは ****_jgw_gw なので Gw::Database を継承
class Gwworkflow::Doc < Gw::Database
  include System::Model::Base
  include System::Model::Base::Content
  include Cms::Model::Base::Content
  include Gwboard::Model::Recognition
  include Gwworkflow::Model::Systemname
  # テーブル名を明示的に指定
  set_table_name 'gw_workflow_docs'
  
  
  has_many :steps, :class_name => 'Gwworkflow::Step', :foreign_key => :doc_id,
    :dependent => :destroy

  validates :title, :presence => true, :length => { :maximum => 140 }
    
  validates :expired_at, :presence => true

  validate :date_valid?
  def date_valid?
      # errors.add('期限日', 'は現在よりも後に設定してください。') if expired_at <= DateTime.now
  end
  validate :committees_valid?
  def committees_valid?
    errors.add('承認ステップ', 'を少なくとも1つ設定してください。') if steps.length == 0
  end
  
  after_validation :delete_route
  def delete_route
    if errors.size > 0
      steps.each{|s|s.destroy}
    end
  end
  
  # 条件を指定して取得
  scope :find_by_conditions, ->(options={}){
    filter = options[:filter] ? options[:filter].to_sym : :all
    type = options[:type] ? options[:type].to_sym : :committed
    state = options[:state] ? options[:state].to_sym : :all
    offset = options[:offset] ? options[:offset].to_i : 0
    limit = options[:limit] ? options[:limit].to_i : 20

    sts = case type
      when :committed then [:draft, :accepted, :rejected, :remanded, :applying]
      when :processing then [:applying] 
      when :accepted then [:accepted, :rejected, :remanded, :applying]
      else [] # これら以外で表示するもの
      end
      
    docs = case type
    when :committed
      where(arel_table[:creater_id].eq(Site.user.id))
    when :processing
      all.select{|doc|
        cs = doc.current_step
        cs ? cs.committee.user_id == Site.user.id : false
      }
    when :accepted
      all.select{|doc|
        doc.steps.any?{|step|
          (step.committee.user_id == Site.user.id) && (step.committee.state == 'accepted')
        }
      }
    else []
    end
    docs = docs.select{|doc| sts.any?{|s| doc.real_state == s} }
      .select{|doc| filter == :all || doc.real_state == filter}
  }
  
  
  def real_state
    if state.to_sym == :applying
       return :accepted if steps.all?{|step| step.state == :accepted }
       return :rejected if steps.any?{|step| step.state == :rejected }
       return :remanded if steps.any?{|step| step.state == :remanded }
    else
    end
    return state.to_sym
  end
  def sorted_steps
    steps.sort{|a,b|a.number <=> b.number}
  end
  
  def total_steps
    steps.length
  end
  
  def now_step
    s = current_step
    s ? s.number : total_steps
  end
  def current_step
    sorted_steps.detect{|step| step.state.to_sym != :accepted }
    #raise sorted_steps.map{|s| "#{s.committee.user_name}-#{s.state.to_s}-#{s.number.to_s}; " }.to_s
  end
  
  def fixed_steps
    sorted_steps.select{|step| step.accepted? }
  end
  
  def future_steps
    sorted_steps.select{|step| step.number > current_step.number }
  end
  
  def fixed_committees
    fixed_steps.map{|step| step.committee }
  end
  
  def future_committees
    future_steps.map{|step| step.committee }
  end
  
  def readable?
    return true
  end

  def creatable?
    return true
  end

  def editable?
    return true
  end

  def deletable?
    return true
  end

end

app/controllers/gwcircular/admin/docs_controller.rb
# -*- encoding: utf-8 -*-
class Gwcircular::Admin::DocsController < Gw::Controller::Admin::Base

  include Gwboard::Controller::Scaffold
  include Gwboard::Controller::Common
  include Gwcircular::Model::DbnameAlias
  include Gwcircular::Controller::Authorize
  layout "admin/template/gwcircular"


  rescue_from ActionController::InvalidAuthenticityToken, :with => :invalidtoken

  def pre_dispatch
    params[:title_id] = 1
    @title = Gwcircular::Control.find_by_id(params[:title_id])
    return http_error(404) unless @title

    Page.title = "回覧板"
    @css = ["/_common/themes/gw/css/circular.css"]

    s_state = ''
    s_state = "?state=#{params[:state]}" unless params[:state].blank?
    return redirect_to("#{Site.current_node.public_uri}#{s_state}") if params[:reset]
    
    params[:limit] = @title.default_limit unless @title.default_limit.blank?
    unless params[:id].blank?
      item = Gwcircular::Doc.find(params[:id])
      unless item.blank?
        if item.doc_type == 0
          params[:cond] = 'owner'
        end
        if item.doc_type == 1
          params[:cond] = 'unread' if item.state == 'unread'
          params[:cond] = 'already' if item.state == 'already'
        end
      end
    end
  end

  def index
    redirect_to "#{@title.item_home_path}"
  end

  def show
    get_role_index
    return authentication_error(403) unless @is_readable

    admin_flags(@title.id)

    item = Gwcircular::Doc.new
    item.and :id, params[:id]
    item.and :state ,'!=', 'preparation'
    @item = item.find(:first)
    return http_error(404) if @item.blank?

    get_role_show(@item)  #admin, readable, editable
    @is_readable = false unless @item.target_user_code == Site.user.code unless @is_admin
    return authentication_error(403) unless @is_readable

    if @item.state == 'unread'
      @item.state = 'already'
      @item.published_at = Time.now
      @item.latest_updated_at = Time.now
      update_creater_editor_circular
      @item._commission_count = true
      @item.save
      params[:cond] = 'already'
    end unless @item.confirmation == 1

    @parent = Gwcircular::Doc.find_by_id(@item.parent_id)
    return http_error(404) unless @parent

    commission_index
  end

  def commission_index(no_paginate=nil)
    item = Gwcircular::Doc.new
    item.and :title_id , @title.id
    item.and :doc_type , 1
    item.and :state ,'!=', 'preparation'
    item.and :parent_id, @item.parent_id
    item.and :target_user_code,'!=', Site.user.code
    item.search(params)
    item.page(params[:page], params[:limit]) if no_paginate.blank?
    @commissions = item.find(:all)
  end

  def edit
    get_role_new
    return authentication_error(403) unless @is_writable

    item = Gwcircular::Doc.new
    item.and :id, params[:id]
    item.and :state ,'!=', 'preparation'
    @item = item.find(:first)
    return http_error(404) unless @item
    get_role_edit(@item)

    @is_readable = false unless @item.target_user_code == Site.user.code unless @is_admin
    return authentication_error(403) unless @is_editable
    @parent = Gwcircular::Doc.find_by_id(@item.parent_id)
    return http_error(404) unless @parent
    Page.title = @title.title
  end

  def update
    get_role_new
    return authentication_error(403) unless @is_writable
    @item = Gwcircular::Doc.find_by_id(params[:id])
    return http_error(404) unless @item

    @parent = Gwcircular::Doc.find_by_id(@item.parent_id)

    @is_writable = false unless @item.target_user_code == Site.user.code unless @is_admin
    return authentication_error(403) unless @is_writable

    @before_state = @item.state
    @item.attributes = params[:item]

    if @before_state == 'unread'
      @item.published_at = Time.now
    end if @item.published_at.blank?

    @item.latest_updated_at = Time.now
    update_creater_editor_circular
    @item._commission_count = true
    location = "#{@item.show_path}?cond=#{params[:cond]}"
 
    _update(@item, :success_redirect_uri=>location)
  end

  def already_update
    get_role_new
    return authentication_error(403) unless @is_writable
    @item = Gwcircular::Doc.find_by_id(params[:id])
    return http_error(404) unless @item

    @is_writable = false unless @item.target_user_code == Site.user.code unless @is_admin
    return authentication_error(403) unless @is_writable
    @item.state = 'already'
    @item.latest_updated_at = Time.now
    @item.published_at = Time.now
    update_creater_editor_circular
    @item._commission_count = true
    @item.save
    location = "#{@item.show_path}?cond=already"
    redirect_to location
  end

  private
  def invalidtoken
    return http_error(404)
  end
end

app/helpers/digitallibrary/admin/docs_helper.rb
module Digitallibrary::Admin::DocsHelper

  def new_digitallib_qstring()
    ret = ""
    ret += "&cat=#{params[:cat]}" unless params[:cat].blank?
    ret += "&limit=#{params[:limit]}" unless params[:limit].blank?
    return ret
  end

  def folder_digitallib_qstring(item)
    ret = "?title_id=#{item.title_id}&cat=#{item.id}"
    ret += "&limit=#{params[:limit]}" unless params[:limit].blank?
    return ret
  end

  def digitallib_uri_params
    if params.blank?
      state = 'CATEGORY'
    else
      state = params[:state]
    end
    base_path = "&state=#{state}"
    if state=='GROUP'
      ret = base_path+"&grp=#{params[:grp]}&gcd=#{params[:gcd]}"
    else
      ret = base_path+"&cat=#{params[:cat]}"
    end
    return ret
  end

  def cat_params(item)
     return "" if item.blank?
     return "&cat=#{item.parent_id.to_s}" unless item.parent_id.blank?
     return "&cat=#{item.id}"
  end

end

app/helpers/doclibrary/admin/docs_helper.rb
module Doclibrary::Admin::DocsHelper

  def new_doclib_category_qstring()
    return "&cat=#{params[:cat]}"
  end

  def folder_doclib_category_qstring(item)
    ret = "?title_id=#{item.title_id}"
    ret += "&state=#{params[:state]}"
    ret += "&gcd=#{item.code}" if params[:state] == 'GROUP'
    ret += "&cat=#{item.id}" unless params[:state] == 'GROUP'
    ret += "#{ret}&limit=#{params[:limit]}" unless params[:limit].blank?
    return ret
  end

  def doclib_uri_params
    state = params[:state]
    base_path = "&state=#{state}"
    if state=='GROUP'
      ret = base_path+"&grp=#{params[:grp]}&gcd=#{params[:gcd]}"
    else
      ret = base_path+"&cat=#{params[:cat]}"
    end
    return ret
  end

  def doclibrary_show_uri(item,prms=nil)
    if prms.blank?
      state = 'CATEGORY'
    else
      state = prms[:state]
    end
    ret = "#{doclibrary_docs_path}/#{item.id}/?title_id=#{item.title_id}" if state == 'GROUP'
    ret = "#{doclibrary_docs_path}/#{item.id}/?title_id=#{item.title_id}" if state == 'DATE'
    ret = "#{doclibrary_docs_path}/#{item.id}/?title_id=#{item.title_id}&cat=#{item.category1_id}" unless state == 'GROUP' unless state == 'DATE'
    return ret
  end

end

app/helpers/gwbbs/admin/docs_helper.rb
# encoding: utf-8
module Gwbbs::Admin::DocsHelper

  def is_comment_delete(section_code, editor_id, is_admin)
    ret = false
    ret = true if is_admin
    ret = true if section_code == Core.user_group.code
    ret = true if editor_id == Core.user.code
    return ret
  end

  def section_bbs_create_link
    title = Gwbbs::Control.find_by_create_section(Core.user_group.code)
    str = ''
    if title.blank?
      str += '<div class="btsHeaderLeft"><span class="btSectionNew">'
      str += link_to('自所属掲示板の新規作成','/gwbbs/builders/')
      str += '</span></div>'
    end
    return str.html_safe
  end

  def doc_size_usage_rate
    body_size_capacity = 0
    body_size_currently = 0
    body_size_capacity = @title.doc_body_size_capacity unless @title.doc_body_size_capacity.blank?
    body_size_currently = @title.doc_body_size_currently unless @title.doc_body_size_currently.blank?
    msg = ""
    return msg if body_size_capacity == 0
    return msg if body_size_currently == 0
    usage = 0
    usage = body_size_currently.to_f / body_size_capacity.megabytes.to_f unless body_size_capacity.megabytes.to_f == 0
    usage = usage * 100
    msg = "　記事本文使用量 #{body_size_currently}バイト" if usage < 1
    msg = "　記事本文容量利用率 #{sprintf('%.04g', usage)}%" if 1 <= usage
    msg = required("<br />#{msg} 　※制限値に近付いています。　不要な記事を削除するか、管理者に連絡してください。") if 90 < usage if usage <= 99.9999
    msg = required("<br />#{msg} 　※制限値を超過しました。　不要な記事を削除するか、管理者に連絡してください。") if 100 <= usage
    return msg
  end

  def admin_doc_size_usage_rate
    body_size_capacity = 0
    body_size_currently = 0
    body_size_capacity = @item.doc_body_size_capacity unless @item.doc_body_size_capacity.blank?
    body_size_currently = @item.doc_body_size_currently unless @item.doc_body_size_currently.blank?
    msg = ""
    return msg if body_size_capacity == 0
    return msg if body_size_currently == 0
    usage = 0
    usage = body_size_currently.to_f / body_size_capacity.megabytes.to_f unless body_size_capacity.megabytes.to_f == 0
    usage = usage * 100
    msg = "　記事本文使用量は #{body_size_currently}バイトです。" if usage < 1
    msg = "　記事本文利用率は #{sprintf('%.04g', usage)}%です。"  if 1 <= usage
    msg = required(" ※#{msg} 制限値に近付いています。") if 90 < usage if usage <= 99.9999
    msg = required(" ※#{msg} 制限値を超過しました。") if 100 <= usage
    return msg
  end
end

app/helpers/gwcircular/docs_helper.rb
#encoding:utf-8
module Gwcircular::DocsHelper

  def gwcircular_attachments_form(form, item)
    form_id = '' if form_id.blank?
    return render(:partial => 'gwcircular/admin/tool/attachments/form', :locals => {:f => form, :item => item})
  end

  def readers_table(title, objects, col, s_class)
    ret = ''
    ret += %Q[<table class="#{s_class}">]
    ret += %Q[<tr><th colspan="#{col}">#{title}</th></tr>]
    i=0
    s_table = ''
    for object in objects
      if col <= i
        i = 0
        s_table += '</tr>'
      end
      s_table += '<tr>' if i == 0
      s_table += %Q[<td style="width: auto;">・#{object[2]}&nbsp;</td>]
      i += 1
    end
    unless i == 0
      j = col - i
      for i in 1..j
        s_table += %Q[<td style="width: auto;"></td>]
      end
      s_table += '</tr>'
    end
    ret += s_table
    ret += '</table>'
    return ret
  end
end

app/helpers/gwmonitor/docs_helper.rb
# -*- encoding: utf-8 -*-
module Gwmonitor::DocsHelper

  def gwmonitor_attachments_form(form, item)
    form_id = '' if form_id.blank?
    return render(:partial => 'gwmonitor/admin/tool/attachments/form', :locals => {:f => form, :item => item})
  end

  def disp_expiry_date(expiry_date,item)
    ret = ''
    unless expiry_date.blank?
      ret = expiry_date.strftime('%Y-%m-%d %H:%M').to_s
      red_set = false
      red_set = true if expiry_date < Time.now
      red_set = true if item.state == 'closed' unless item.blank?
      ret = %Q[<span style="color:red">#{ret}</span>] if red_set
    end
    return ret
  end

  def is_gwmonitor_admin?
    ret = false
    ret = true if System::Model::Role.get(1, Site.user.id ,'gwmonitor', 'admin')
    ret = true if System::Model::Role.get(2, Site.user_group.id ,'gwmonitor', 'admin') unless ret
    return ret
  end

  def gwmonitor_settings
    ret = %Q[<span class="btSet"><a href="/gwmonitor/custom_groups">設定</a></span>]
    ret = %Q[<span class="btSetAdd"><a href="/gwmonitor/settings">管理者</a></span>] if is_gwmonitor_admin?
    return ret
  end

  def gwmonitor_base_attachments_form(form, item)
    form_id = '' if form_id.blank?
    return render(:partial => 'gwmonitor/admin/tool/base_attachments/form', :locals => {:f => form, :item => item})
  end

  def monitor_readers_table(title, objects, col, s_class, width)
    ret = ''
    ret += %Q[<table class="#{s_class}">]
    ret += %Q[<tr><th colspan="#{col}">#{title}</th></tr>]
    i=0
    s_table = ''
    for object in objects
      if col <= i
        i = 0
        s_table += '</tr>'
      end
      s_table += '<tr>' if i == 0
      s_table += %Q[<td style="width: #{width};">#{object[2]}&nbsp;</td>]
      i += 1
    end
    unless i == 0
      j = col - i
      for i in 1..j
        s_table += %Q[<td style="width: #{width};"></td>]
      end
      s_table += '</tr>'
    end
    ret += s_table
    ret += '</table>'
    return ret
  end

end

app/views/gwboard/admin/docs/_file_memo_form.html.erb
<div class="docsInnerBox">
<table class="gwboardAttachlist">
  <tr>
    <th colspan="2">添付ファイル名</th>
    <th class="remark">備考</th>
  </tr>
    <tr>
      <td style="width:30px;" class="attachIcon"><%= link_to '', '#', :class => @file.icon_type %></td>
      <td><%= "#{@file.filename} (#{@file.eng_unit})" %></td>
      <td class="remark"><%= f.text_field :memo, :size => 30 %></td>
    </tr>
</table>
</div>

app/views/gwboard/admin/docs/_library_index.html.erb
<%
show_all_attachment_files = true
#旧設定では表示させないように注意が必要
unless show_all_attachment_files
  #画像以外のファイルがある時は表示する
  dsp_flag = @files.find{|file| !file.is_image} ? true : false
end
%>
<% if @files.size > 0 && (show_all_attachment_files || dsp_flag) %>
<div class="docsInnerBox2">
<table class="gwboardAttachlist">
<tr><th colspan="2">添付ファイル名</th></tr>
<% for item in @files %>
  <% download_url = "#{item.file_uri(item.system_name)}" %>
  <% if show_all_attachment_files || !item.is_image %>
   <tr>
   <td style="width:30px;" class="attachIcon"><%= link_to '', download_url, :class => item.icon_type %></td>
   <td><%= link_to "#{item.filename} (#{item.eng_unit})", download_url %></td>
   </tr>
  <% end %>
<% end %>
</table>
</div>
<% end %>

app/views/gwboard/admin/docs/_library_index_mobile.html.erb
<%
#旧設定では表示させないように注意が必要
dsp_flag = false
for item in @files
  dsp_flag = true unless item.is_image  #画像以外のファイルがある時は表示する
end unless @files.blank?
%>
<%if dsp_flag %>
<p class="bgAsh">添付ファイル</p>

<%
for item in @files
  download_url = "#{item.file_uri(item.system_name)}"
%>
<%unless item.is_image %>
<p class="leftPad2"><%= link_to(%Q[#{item.filename} (#{item.eng_unit})],download_url) %></p>
<%end%>
<%
end %>
<span style="color: #ff0000;">※パケット定額サービスに入っていない場合、高額の通信料が発生する場合があります。</span>
<%end%>

app/views/gwboard/admin/docs/_library_index_mobile_smartphone.html.erb
<%
#旧設定では表示させないように注意が必要
dsp_flag = false
for item in @files
  dsp_flag = true unless item.is_image  #画像以外のファイルがある時は表示する
end unless @files.blank?
%>
<%if dsp_flag %>
<div class="docsInnerBox2">
<table class="gwboardAttachlist">
<tr><th colspan="2">添付ファイル名</th></tr>
<%
for item in @files
  download_url = "#{item.file_uri(item.system_name)}"
%>
<%unless item.is_image %>
 <tr>
 <td style="width:30px;" class="attachIcon"><%= link_to('',download_url,:class => item.icon_type) %></td>
 <td><%= link_to(%Q[#{item.filename} (#{item.eng_unit})],download_url) %></td>
 </tr>
<%end%>
<%
end %>
</table>
</div>
<span style="color: #ff0000;">※パケット定額サービスに入っていない場合、高額の通信料が発生する場合があります。</span>
<%end%>

app/views/gwboard/admin/docs/_library_index_wm.html.erb
<%
show_all_attachment_files = true
#旧設定では表示させないように注意が必要
unless show_all_attachment_files
  #画像以外のファイルがある時は表示する
  dsp_flag = @files.find{|file| !file.is_image} ? true : false
end
%>
<% if @files.size > 0 && (show_all_attachment_files || dsp_flag) %>
<div class="docsInnerBox2">
<table class="gwboardAttachlist">
<tr>
  <th colspan="2">添付ファイル名</th>
  <th class="remark">備考</th>
</tr>
<% for item in @files %>
  <% download_url = "#{item.file_uri(item.system_name)}" %>
  <% if show_all_attachment_files || !item.is_image %>
  <tr>
    <td style="width:30px;" class="attachIcon"><%= link_to '', download_url, :class => item.icon_type %></td>
    <td><%= link_to "#{item.filename} (#{item.eng_unit})", download_url %></td>
    <td class="remark">
    <%# 電子図書で編集権があれば、添付ファイルの備考欄編集を表示 %>
    <% if @is_editable %>
      <%= link_to '編集', "#{item.edit_memo_path(@title,@item)}#{doclib_params_set}" if @item.doc_alias == 0 && item.system_name == 'digitallibrary' %>
    <% end %>
    <%= item.memo %>
    </td>
  </tr>
  <% end %>
<% end %>
</table>
</div>
<% end %>

app/views/gwboard/admin/docs/_upload_index.html.erb
<% unless @files.blank? %>
<div class="docsInnerBox2">
<table class="gwboardAttachlist">
<tr>
  <th colspan="2">添付ファイル名</th>
  <th class="remark">備考</th>
</tr>
<%
for item in @files
  #全ての処理に同じ対応が済むまで(掲示板のみ)
  case item.system_name.to_s
  when "gwbbs", "gwfaq"
    case @title.upload_system
    when 1..4
      download_url = "#{item.file_uri(item.system_name)}"
    else
      download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
    end
  else
    download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
  end
%>
<tr>
  <td style="width:30px;" class="attachIcon"><%= link_to '', download_url, :class => item.icon_type %></td>
  <td><%= link_to(%Q[#{item.filename} (#{item.eng_unit})],download_url) %></td>
  <td class="remark">
  <%# 書庫・電子図書で編集権があれば、添付ファイルの備考欄編集を表示 %>
  <% if @is_editable %>
    <% case item.system_name %>
    <% when 'gwbbs' %>
      <%= link_to '編集', "#{item.edit_memo_path(@title,@item)}#{gwbbs_params_set}" %>
    <% when 'doclibrary' %>
      <%= link_to '編集', "#{item.edit_memo_path(@title,@item)}#{doclib_params_set}" %>
    <% when 'digitallibrary' %>
      <%= link_to '編集', "#{item.edit_memo_path(@title,@item)}#{doclib_params_set}" if @item.doc_alias == 0 %>
    <% end %>
  <% end %>
  <%= item.memo %>
  </td>
</tr>
<% end %>
</table>
</div>
<% end %>

app/views/gwboard/admin/docs/_upload_index_mobile.html.erb
<%unless @files.blank?%>
<p class="bgAsh">添付ファイル</p>
<%
for item in @files
  #全ての処理に同じ対応が済むまで(掲示板のみ)
  case item.system_name.to_s
  when "gwbbs", "gwfaq"
    download_url = "#{item.file_uri(item.system_name)}" if @title.upload_system == 1
    download_url = "#{item.file_uri(item.system_name)}" if @title.upload_system == 2
    unless @title.upload_system == 1
      download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
    end unless @title.upload_system == 2
  else
    download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
  end
%>
<p class="leftPad2"><%= link_to(%Q[#{item.filename} (#{item.eng_unit})],download_url) %></p>
<p class="leftPad1"><%=item.memo%></p>
<%
end %>
<span style="color: #ff0000;">※パケット定額サービスに入っていない場合、高額の通信料が発生する場合があります。</span>
<%end%>

app/views/gwboard/admin/docs/_upload_index_mobile_smartphone.html.erb
<%unless @files.blank?%>
<div class="docsInnerBox2">
<table class="gwboardAttachlist">
<tr>
<th colspan="2">添付ファイル名</th>
<th class="remark">備考</th>
</tr>
<%
for item in @files
  #全ての処理に同じ対応が済むまで(掲示板のみ)
  case item.system_name.to_s
  when "gwbbs", "gwfaq"
    download_url = "#{item.file_uri(item.system_name)}" if @title.upload_system == 1
    download_url = "#{item.file_uri(item.system_name)}" if @title.upload_system == 2
    unless @title.upload_system == 1
      download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
    end unless @title.upload_system == 2
  else
    download_url = "/_admin/gwboard/receipts/#{item.id}/download_object?system=#{item.system_name}&title_id=#{item.title_id}"
  end
%>
 <tr>
 <td style="width:30px;" class="attachIcon"><%= link_to('',download_url,:class => item.icon_type) %></td>
 <td><%= link_to(%Q[#{item.filename} (#{item.eng_unit})],download_url) %></td>
 <td class="remark">
 <%# 書庫・電子図書で編集権があれば、添付ファイルの備考欄編集を表示 %>
 <%=item.memo%>
 </td>
 </tr>
<%
end %>
</table>
</div>
<span style="color: #ff0000;">※パケット定額サービスに入っていない場合、高額の通信料が発生する場合があります。</span>
<%end%>